def main():
    print(r"      ___           ___                   ")
    print(r"     /  /\         /  /\          ___     ")
    print(r"    /  /::|       /  /::\        /  /\    ")
    print(r"   /  /:|:|      /  /:/\:\      /  /::\   ")
    print(r"  /  /:/|:|__   /  /:/  \:\    /  /:/\:\  ")
    print(r" /__/:/_|::::\ /__/:/ \  \:\  /  /::\ \:\ ")
    print(r" \__\/  /~~/:/ \  \:\  \__\/ /__/:/\:\_\:\ ")
    print(r"       /  /:/   \  \:\       \__\/  \:\/:/")
    print(r"      /  /:/     \  \:\           \  \::/ ")
    print(r"     /__/:/       \  \:\           \__\/  ")
    print(r"     \__\/         \__\/                  ")
    print(r"      ___           ___           ___           ___                   ")
    print(r"     /  /\         /  /\         /  /\         /  /\          ___     ")
    print(r"    /  /::\       /  /::\       /  /::\       /  /::|        /__/\    ")
    print(r"   /  /:/\:\     /  /:/\:\     /  /:/\:\     /  /:|:|        \  \:\   ")
    print(r"  /  /::\ \:\   /  /:/  \:\   /  /::\ \:\   /  /:/|:|__       \__\:\  ")
    print(r" /__/:/\:\_\:\ /__/:/_\_ \:\ /__/:/\:\ \:\ /__/:/ |:| /\      /  /::\ ")
    print(r" \__\/  \:\/:/ \  \:\__/\_\/ \  \:\ \:\_\/ \__\/  |:|/:/     /  /:/\:\ ")
    print(r"      \__\::/   \  \:\ \:\    \  \:\ \:\       |  |:/:/     /  /:/__\/")
    print(r"      /  /:/     \  \:\/:/     \  \:\_\/       |__|::/     /__/:/     ")
    print(r"     /__/:/       \  \::/       \  \:\         /__/:/      \__\/      ")
    print(r"     \__\/         \__\/         \__\/         \__\/                  ")
    print(r"      ___           ___     ")
    print(r"     /  /\         /  /\    ")
    print(r"    /  /::\       /  /::\   ")
    print(r"   /  /:/\:\     /  /:/\:\  ")
    print(r"  /  /::\ \:\   /  /::\ \:\ ")
    print(r" /__/:/\:\_\:\ /__/:/\:\ \:\ ")
    print(r" \__\/~|::\/:/ \  \:\ \:\_\/")
    print(r"    |  |:|::/   \  \:\ \:\  ")
    print(r"    |  |:|\/     \  \:\_\/  ")
    print(r"    |__|:|~       \  \:\    ")
    print(r"     \__\|         \__\/    ")
    
    print("Hello from MCP_Agent:RE!")
    print("This project is designed to help you analyze TAPD data.")
    print("You can use various tools to extract insights from your data.")
    print("For more information, please refer to the README.md file.")

if __name__ == "__main__":
    main()