def main():
    print(r"      ___           ___                    ")
    print(r"     /  /\         /  /\          ___      ")
    print(r"    /  /::|       /  /::\        /  /\     ")
    print(r"   /  /:|:|      /  /:/\:\      /  /::\    ")
    print(r"  /  /:/|:|__   /  /:/  \:\    /  /:/\:\   ")
    print(r" /__/:/_|::::\ /__/:/ \  \:\  /  /::\ \:\  ")
    print(r" \__\/  /~~/:/ \  \:\  \__\/ /__/:/\:\_\:\ ")
    print(r"       /  /:/   \  \:\       \__\/  \:\/:/ ")
    print(r"      /  /:/     \  \:\           \  \::/  ")
    print(r"     /__/:/       \  \:\           \__\/   ")
    print(r"     \__\/         \__\/                   ")
    print(r"      ___           ___           ___           ___                    ")
    print(r"     /  /\         /  /\         /  /\         /  /\          ___      ")
    print(r"    /  /::\       /  /::\       /  /::\       /  /::|        /__/\     ")
    print(r"   /  /:/\:\     /  /:/\:\     /  /:/\:\     /  /:|:|        \  \:\    ")
    print(r"  /  /::\ \:\   /  /:/  \:\   /  /::\ \:\   /  /:/|:|__       \__\:\   ")
    print(r" /__/:/\:\_\:\ /__/:/_\_ \:\ /__/:/\:\ \:\ /__/:/ |:| /\      /  /::\  ")
    print(r" \__\/  \:\/:/ \  \:\__/\_\/ \  \:\ \:\_\/ \__\/  |:|/:/     /  /:/\:\ ")
    print(r"      \__\::/   \  \:\ \:\    \  \:\ \:\       |  |:/:/     /  /:/__\/ ")
    print(r"      /  /:/     \  \:\/:/     \  \:\_\/       |__|::/     /__/:/      ")
    print(r"     /__/:/       \  \::/       \  \:\         /__/:/      \__\/       ")
    print(r"     \__\/         \__\/         \__\/         \__\/                   ")
    print(r"      ___           ___      ")
    print(r"     /  /\         /  /\     ")
    print(r"    /  /::\       /  /::\    ")
    print(r"   /  /:/\:\     /  /:/\:\   ")
    print(r"  /  /::\ \:\   /  /::\ \:\  ")
    print(r" /__/:/\:\_\:\ /__/:/\:\ \:\ ")
    print(r" \__\/~|::\/:/ \  \:\ \:\_\/ ")
    print(r"    |  |:|::/   \  \:\ \:\   ")
    print(r"    |  |:|\/     \  \:\_\/   ")
    print(r"    |__|:|~       \  \:\     ")
    print(r"     \__\|         \__\/     ")
    print("")
    print("欢迎来到 MCP_Agent:RE!")
    print("Hello from MCP_Agent:RE!")
    print("")
    print("这个项目旨在帮助您分析 TAPD 数据。")
    print("This project is designed to help you analyze TAPD data.")
    print("")
    print("您可以使用各种工具以提取您的 TAPD 数据。")
    print("You can use various tools to extract your TAPD data.")
    print("")
    print("有关更多信息，请参阅 README.md 文件。")
    print("For more information, please refer to the README.md file.")
    print("")

if __name__ == "__main__":
    main()